fix for working with empty arrays
Is creating following error message since ZF 1.5

Zend_Db_Statement_Exception: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
/data/www/sites/mwdev/erp1.mwdev.net/htdocs/tine20/Tinebase/Container.php:475

git-svn-id: file:///www/metaways/svn.tine20.org/repo/trunk/tine20@1243 8d11cdf3-9d2f-0410-bbb5-e098f187f06b